#!/usr/bin/env python

top = '../..'

def build(ctx):
	tgt = '../../bin/serialosc-detector'

	if ctx.env.DEST_OS[:3] == "win":
		ctx.program(
			source='windows.c',
			target=tgt,
			use='serialosc-common')
	elif ctx.env.DEST_OS == 'linux':
		ctx.program(
			source='libudev.c',
			target=tgt,
			use='serialosc-common UDEV')
	elif ctx.env.DEST_OS == 'darwin':
		ctx.program(
			source='iokitlib.c',
			target=tgt,
			use='serialosc-common',
			framework=['IOKit', 'CoreFoundation'])
	else:
		ctx.fatal('''Couldn't find a detector module for your platform.''')
