#!/usr/bin/env python

top = '..'

def build_common(ctx):
	objs = []
	obj = lambda src: objs.append(src)

	if ctx.env.DEST_OS[:3] == "win":
		obj('common/platform/windows.c')
	else:
		obj('common/platform/posix.c')

		if ctx.env.DEST_OS == 'linux':
			obj('common/platform/linux.c')
		elif ctx.env.DEST_OS == 'darwin':
			obj('common/platform/darwin.c')

	obj('common/ipc.c')
	obj('common/util.c')

	ctx.stlib(
		source=objs,
		target='serialosc-common',
		use='serialosc-include')

def build(ctx):
	ctx(export_includes=['..', '../include', '../third-party', '../third-party/confuse'],
			name='serialosc-include')

	build_common(ctx)

	ctx.recurse('serialoscd')
	ctx.recurse('serialosc-detector')
	ctx.recurse('serialosc-device')
